sensor:
  - platform: snmp
    name: wan_in
    baseoid: 1.3.6.1.2.1.2.2.1.10.4
    host: 192.168.4.1
    accept_errors: true
    scan_interval: 10
  - platform: snmp
    name: wan_out
    baseoid: 1.3.6.1.2.1.2.2.1.16.4
    host: 192.168.4.1
    accept_errors: true
    scan_interval: 10
  - platform: derivative
    name: wan_in_der
    source: sensor.wan_in
    unit_time: s
    unit: B
  - platform: derivative
    name: wan_out_der
    source: sensor.wan_out
    unit_time: s
    unit: B
  - platform: template
    sensors:
      wan_in_mbps:
        value_template:  "{{ [((states('sensor.wan_in_der')|float*8)/1000000)|round(2),0]|max }}"
        unit_of_measurement: 'Mbps'
        entity_id: sensor.wan_in_der
        friendly_name: "WAN In"
      wan_out_mbps:
        value_template:  "{{ [((states('sensor.wan_out_der')|float*8)/1000000)|round(2),0]|max }}"
        unit_of_measurement: 'Mbps'
        entity_id: sensor.wan_out_der
        friendly_name: "WAN Out"
